# Server
server.port=8080

# Database - Render PostgreSQL (baad mein Render ki URL dalenge)
spring.datasource.url=jdbc:postgresql://dpg-d7rjhgkm0tmc738c15n0-a.oregon-postgres.render.com/gallerydb_av93
spring.datasource.username=gallerydb_av93_user
spring.datasource.password=QnkyiRCJW4h0NC5ElnDA2vDrKslNjQZZ
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Cloudinary
cloudinary.cloud-name=ddzdfpiqr
cloudinary.api-key=586611995461797
cloudinary.api-secret=wzjULW5oiKc_YZk6Z2X-DjzsimA

# JWT
jwt.secret=mySecretKey123456789012345678901234567890
jwt.expiration=2592000000

# File Upload
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# CORS
cors.allowed-origins=http://localhost:3000